CREATE TABLE [dbo].[MENULIST](
	[GROUP] [varchar](50) NOT NULL,
	[SEQUENCE] [numeric](6, 2) NULL,
	[CODE] [varchar](50) NOT NULL,
	[LEVEL] [numeric](4, 0) NOT NULL,
	[NAME] [varchar](80) NOT NULL,
	[NODE] [varchar](50) NOT NULL,
	[PARENT] [varchar](50) NOT NULL,
	[CONTROLLER] [varchar](80) NOT NULL,
	[VIEW] [varchar](80) NULL,
	[PARAMERTER] [varchar](80) NULL,
	[ICON] [varchar](50) NOT NULL,
	[CREATEDBY] [varchar](15) NULL,
	[CREATEDTIME] [datetime] NULL,
	[UPDATEDBY] [varchar](15) NULL,
	[UPDATEDTIME] [datetime] NULL,
 CONSTRAINT [PK_MENULIST] PRIMARY KEY CLUSTERED 
(
	[GROUP] ASC,
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

----------------------
----------------------

CREATE TABLE [dbo].[LEVELMENU](
	[GROUP] [char](10) NULL,
	[MNUCOD] [char](50) NOT NULL,
	[LEVEL] [char](1) NULL,
	[BUSFUNC] [varchar](20) NULL,
	[ISENABLE] [bit] NULL
) ON [PRIMARY]
GO

----------------------
----------------------

CREATE TABLE [dbo].[USER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PLANTCODE] [varchar](4) NOT NULL,
	[USERID] [varchar](100) NOT NULL,
	[USERNAME] [varchar](255) NOT NULL,
	[PASSWORD] [nvarchar](max) NOT NULL,
	[DEPARTMENT] [varchar](100) NOT NULL,
	[EMAIL] [varchar](255) NOT NULL,
	[PHONE] [varchar](20) NOT NULL,
	[BUSINESSFUNCTION] [varchar](50) NOT NULL,
	[PHOTO] [varchar](255) NOT NULL,
	[LINEID] [varchar](10) NOT NULL,
	[ISACTIVE] [bit] NOT NULL,
	[ISWINDOWSAUTHENTICATION] [bit] NOT NULL,
	[LASTLOGINDEVICE] [varchar](50) NULL,
	[LASTLOGINDATE] [datetime] NULL,
	[DOMAINNAME] [varchar](20) NOT NULL,
	[SALUTATION] [varchar](10) NULL,
	[WINDOWSAUTH] [varchar](50) NULL,
	[EMPID] [varchar](50) NULL,
	[CREATEUSER] [varchar](50) NOT NULL,
	[CREATEDATE] [datetime] NOT NULL,
	[CHANGEUSER] [varchar](50) NULL,
	[CHANGEDATE] [datetime] NULL,
	[VERIFICATIONCODE] [nvarchar](50) NULL,
 CONSTRAINT [PK_USER_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_USERID] UNIQUE NONCLUSTERED 
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_PLANTCODE]  DEFAULT ('') FOR [PLANTCODE]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_USERNAME]  DEFAULT ('') FOR [USERNAME]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_PASSWORD]  DEFAULT ('') FOR [PASSWORD]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_DEPARTMENT]  DEFAULT ('') FOR [DEPARTMENT]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_EMAIL]  DEFAULT ('') FOR [EMAIL]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_PHONE]  DEFAULT ('') FOR [PHONE]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_PHOTO]  DEFAULT ('') FOR [PHOTO]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_LINEID]  DEFAULT ('*') FOR [LINEID]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_ISACTIVE]  DEFAULT ((1)) FOR [ISACTIVE]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_ISWINDOWSAUTHENTICATION]  DEFAULT ((0)) FOR [ISWINDOWSAUTHENTICATION]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_DOMAINNAME]  DEFAULT ('SHIMANOACE') FOR [DOMAINNAME]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_CREATEUSER]  DEFAULT ('') FOR [CREATEUSER]
GO

ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_CTUSER_CREATEDATE]  DEFAULT (getdate()) FOR [CREATEDATE]
GO

----------------------
----------------------
CREATE TABLE [dbo].[PLANT](
	[ID] [nvarchar](50) NULL,
	[NAME] [nvarchar](50) NULL,
	[CREATEUSER] [nvarchar](50) NULL,
	[CREATEDATE] [nvarchar](50) NULL,
	[CHANGEUSER] [nvarchar](50) NULL,
	[CHANGEDATE] [nvarchar](50) NULL
) ON [PRIMARY]
GO
----------------------
----------------------
CREATE TABLE [dbo].[GROUP](
	[ID] [nvarchar](50) NULL,
	[NAME] [nvarchar](50) NULL,
	[CREATEUSER] [nvarchar](50) NULL,
	[CREATEDATE] [nvarchar](50) NULL,
	[CHANGEUSER] [nvarchar](50) NULL,
	[CHANGEDATE] [nvarchar](50) NULL
) ON [PRIMARY]
GO
----------------------
----------------------
CREATE TABLE [dbo].[DEPARTMENT](
	[ID] [nvarchar](50) NULL,
	[NAME] [nvarchar](50) NULL,
	[CREATEUSER] [nvarchar](50) NULL,
	[CREATEDATE] [nvarchar](50) NULL,
	[CHANGEUSER] [nvarchar](50) NULL,
	[CHANGEDATE] [nvarchar](50) NULL
) ON [PRIMARY]
GO













---------------------------------------
INSERT INTO [MENULIST]
VALUES ('APP_TEST','1.00','ROOT','0','MAIN MENU','AR','','#','#',NULL,'NAV-ICON FAS FA-HOME','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','2.00','MENU_01','1','MENU 01','MENU_01','AR','HOME','MENU_01',NULL,'FAR FA-FOLDER NAV-ICON','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','3.00','MENU_02','1','MENU 02','MENU_02','AR','HOME','MENU_02',NULL,'FAR FA-FOLDER NAV-ICON','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','4.00','MENU_03','1','MENU 03','MENU_03','AR','HOME','MENU_03',NULL,'FAR FA-FOLDER NAV-ICON','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','5.00','MENU_04','1','MENU 04','MENU_04','AR','HOME','MENU_04',NULL,'FAR FA-FOLDER NAV-ICON','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','6.00','MASTERDATA','0','MASTER DATA','MD','','#','#',NULL,'NAV-ICON FAS FA-DATABASE','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','7.00','MASTER_USER','1','USER','MASTER_USER','MD','MASTER','USER',NULL,'FAR FA-FOLDER NAV-ICON','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','8.00','MASTER_GROUP','1','GROUP','MASTER_GROUP','MD','MASTER','GROUP',NULL,'FAR FA-FOLDER NAV-ICON','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','9.00','MASTER_MENU','1','MENU','MASTER_MENU','MD','MASTER','MENU',NULL,'FAR FA-FOLDER NAV-ICON','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','10.00','MASTER_DEPARTMENT','1','MENU','MASTER_DEPARTMENT','MD','MASTER','DEPARTMENT',NULL,'FAR FA-FOLDER NAV-ICON','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
INSERT INTO [MENULIST]
VALUES ('APP_TEST','11.00','MASTER_PLANT','1','MENU','MASTER_PLANT','MD','MASTER','PLANT',NULL,'FAR FA-FOLDER NAV-ICON','SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
-------------------------------------
INSERT INTO [GROUP]
VALUES ('ADMINISTRATOR', 'ADMINISTRATOR', 'SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
-------------------------------------
INSERT INTO [DEPARTMENT]
VALUES ('IT', 'INFORMATION TECHNOLOGY', 'SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
-------------------------------------
INSERT INTO [PLANT]
VALUES ('0001', 'PLANT 0001', 'SYSTEM', GETDATE(), 'SYSTEM', GETDATE())
-------------------------------------
INSERT INTO [USER] (PLANTCODE, USERID, USERNAME, [PASSWORD], DEPARTMENT, EMAIL, PHONE, BUSINESSFUNCTION, CREATEUSER, CREATEDATE, ISWINDOWSAUTHENTICATION)
VALUES ('0001', 'ADMIN', 'ADMINISTRATOR', PWDENCRYPT('ADMIN'), 'IT', 'email@email.com', '08', 'ADMINISTRATOR', 'SYSTEM-ADMIN', GETDATE(), 0)
-------------------------------------
INSERT INTO LEVELMENU 
SELECT 'APP_TEST', CODE, '', 'ADMINISTRATOR', 1 FROM [MENULIST]
-------------------------------------




